### ISSUE TITLE
Disable aws cli pager

### ISSUE THREAD

**Issue by artkrz** [buildkite-plugins/ecs-deploy-buildkite-plugin#107]
When using the following step:

```
- label: Deploy
    concurrency_group: "cicd-eval-deploy"
    concurrency: 1
    plugins:
      - ecs-deploy#v3.0.0:
          cluster: "cicd-eval"
          service: "cicd-eval-buildkite"
          task-family: "cicd-eval-buildkite"
          image: "xxx.dkr.ecr.us-west-2.amazonaws.com/cicd-eval:${BUILDKITE_BUILD_NUMBER}"
```
deployment stalls:

```
Updating service for cicd-eval-buildkite | 4m 20s
-- | --
  | {
  | "service": {
  | "serviceArn": "arn:aws:ecs:us-west-2:xxx:service/cicd-eval/cicd-eval-buildkite",
  | "serviceName": "cicd-eval-buildkite",
  | "clusterArn": "arn:aws:ecs:us-west-2:xxx:cluster/cicd-eval",
  | "loadBalancers": [],
  | "serviceRegistries": [],
  | "status": "ACTIVE",
  | "desiredCount": 1,
  | "runningCount": 1,
  | "pendingCount": 0,
  | "capacityProviderStrategy": [
  | {
  | "capacityProvider": "FARGATE",
  | "weight": 1,
  | "base": 0
  | }
  | ],
  | "platformVersion": "LATEST",
  | "platformFamily": "Linux",
  | "taskDefinition": "arn:aws:ecs:us-west-2:xxx:task-definition/cicd-eval-buildkite:8",
  | :

```

This is caused by paginated output of task definition json, to mitigate I've added:

```
[default]
cli_pager=
```
 to `~/.aws/config` of `buildkite-agent` user home but this should be addressed by adding `--no-paginate` to all AWS CLI commands.
