### ISSUE TITLE
AWSCLI v2 seems to not work with the auto-fill container definition feature

### ISSUE THREAD

**Issue by huewood** [buildkite-plugins/ecs-deploy-buildkite-plugin#113]
Hey again 👋 

We've been using this plugin excessively and was working very well with our use case. Specifically the new feature added in 3.0 with the auto-fill task definition pulling the latest definition and using that as a base.

Recently though, we upgraded our CI machines to use awscli v2 rather than v1. This has caused this plugin to 'successfully' deploy the service, but the buildkite job will hang until it times out at the [Update Service](https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/blob/master/hooks/command#L173) command.

Could this be investigated and figured out what's going on under the hood? And if it is a hard awscli v1 requirement, please update the documentation to specify that?

I can assist with providing logs for both cases if needed.

Cheers!

**Comment by ryan-keswick** [comment]
I'm getting the same error, I believe its because `update-service` creates a Pager that expects the user to input `q` to exit `less`.

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-awspager

```
export AWS_PAGER=""
```
Tried setting this but it doesn't work either

**Comment by ryan-keswick** [comment]
Put `AWS_PAGER` in the env. 

```
steps:
  - label: ":ecs: :rocket: Deploying XXXXXX"
    if: pipeline.default_branch == build.branch
    concurrency_group: "XXXXXX-XXX"
    concurrency: 1
    depends_on: build
    env:
      # This needs to be set
      AWS_PAGER: ""
    plugins:
      - ecs-deploy#v3.0.0: # See: https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin
        cluster: "XXXXXX-XXX"
        service: "XXXXXX-XXX"
        task-family: "XXXXXX-XXX"
        image: "$$IMAGE:$$TAG"
        region: "us-west-2"
```
