### ISSUE TITLE
Can I deploy to a service that wasn't created by this plugin?

### ISSUE THREAD

**Issue by yob** [buildkite-plugins/ecs-deploy-buildkite-plugin#53]
We have a ECS/fargate service that's managed by terraform. The terraform config includes attaching the service to a target group so it receives traffic from an ALB.

I attempted to use this plugin to deploy a new task definition to the service, and initially I left the target group out of the plugin config as I knew the "create service" code path in the plugin wouldn't be used:

```yaml
    plugins:
      - ecs-deploy#v1.4.1:
          cluster: "cluster-name"
          service: "my-service"
          task-definition: "deploy/task-container-definitions.json"
          task-family: "thing"
          image: "${ECR_REPO}:${BUILDKITE_BUILD_NUMBER}"
          execution-role: "${ECS_EXECUTION_ROLE_ARN}"
```

However, deploys failed with this error:

```
Cannot update a service to add/remove a load balancer. First delete the service
and then run again, or rename the service to force a new one to be created.
Container config differs
```

I then assumed I might need to include the target group config, even though it wouldn't be used, so I tried this config:

```yaml
    plugins:
      - ecs-deploy#v1.4.1:
          cluster: "cluster-name"
          service: "my-service"
          task-definition: "deploy/task-container-definitions.json"
          task-family: "thing"
          image: "${ECR_REPO}:${BUILDKITE_BUILD_NUMBER}"
          execution-role: "${ECS_EXECUTION_ROLE_ARN}"
          target-container-name: web
          target-container-port: 3000
```

However, deploys failed with this error:

```
Registering new task definition for thing
Registered thing:16
🚨 Error: The command exited with status 1
```

To confirm the agent running the step has the necessary IAM permissions, I tried a minimal deploy shell script with some sugar around the following commands and it seems to work:

```
aws ecs register-task-definition --cli-input-json ...
aws ecs update-service ...
aws ecs wait services-stable ...
```
