### ISSUE TITLE
Trying to deploy to an existing cluster, recieving an 'unbound variable' error 

### ISSUE THREAD

**Issue by lhatfield** [buildkite-plugins/ecs-deploy-buildkite-plugin#81]
Full error: /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-ecs-deploy-buildkite-plugin-v2-0-0/hooks/command: line 136: env_vars[@]: unbound variable

```
  - label: ":ecs: :rocket:"

    concurrency_group: "my-service-deploy"
    
    concurrency: 1
    
    plugins:
    
      - ecs-deploy#v1.4.1:
      
          cluster: "<existing cluster>"
          
          service: "<non-existent service>"
          
          task-definition: "deploy/containers.json"
          
          task-family: "<task family>"
          
          image: "<arn>/<image>:latest"
          
          target-group: "<existing targetgroup-arn>"
          
          target-container-port: 3000
          
```
containers.json

```


[
{ 
"essential": true,
    
    "image": "<taskdef arn>",
    
    "memory": 1024,
    
    "name": "sample",
    
    "portMappings": [
    
      {
        "containerPort": 3000,
        
        "hostPort": 3000
        
      }
      
    ]
  }
]

```

I have tried pointing to a different service without a target group and ALB in front of it and still get the same sort of issue. I think Im missing some information on the launching of the fargate containers.

**Comment by ouranos** [comment]
I had the same issue with `v2.0.0`, I got rid of it by setting environment variables in this format:
```yaml
  - label: ":ecs: :rocket:"
    plugins:
      - ecs-deploy#v2.0.0:
          cluster: "<existing cluster>"
          service: "<non-existent service>"
          task-family: "<task family>"
          image: "<arn>/<image>:latest"
          container-definitions: "deploy/containers.json"
          env:
            - "FOO=BAR"
```
